export enum AuthActionsTypes {
  REGISTER = "[AUTH] REGISTER",
  REGISTER_SUCCESS = "[AUTH] REGISTER_SUCCESS",
  REGISTER_ERROR = "[AUTH] REGISTER_ERROR",

  LOGIN = "[AUTH] LOGIN",
  LOGIN_SUCCESS = "[AUTH] LOGIN_SUCCESS",
  LOGIN_ERROR = "[AUTH] LOGIN_ERROR",

  LOG_OUT = "[AUTH] LOG_OUT",
  LOG_OUT_SUCCESS = "[AUTH] LOG_OUT_SUCCESS",
  LOG_OUT_ERROR = "[AUTH] LOG_OUT_ERROR",
}

export enum PaintActionsTypes {
  SET_TOOL = "[DRAW] SET_TOOL",

  SET_THICKNESS = "[DRAW] SET_THICKNESS",

  SET_COLOR = "[DRAW] SET_COLOR",

  GET_ALL_PICS = "[DRAW] GET_ALL_PICS",
  GET_ALL_PICS_SUCCESS = "[DRAW] GET_ALL_PICS_SUCCESS",
  GET_ALL_PICS_ERROR = "[DRAW] GET_ALL_PICS_ERROR",

  SEND_PIC = "[DRAW] SEND_PIC",
  SEND_PIC_SUCCESS = "[DRAW] SEND_PIC_SUCCESS",
  SEND_PIC_ERROR = "[DRAW] SEND_PIC_ERROR",

  GET_SEARCH_EMAIL = "[DRAW] SEARCH_EMAIL",
}
